#! /usr/bin/env python3

#-----------------------------------------------------------------------
import apt

#-----------------------------------------------------------------------
if __name__ == '__main__':
	cache = None
	hit = {}
	ret = None
	
	try:
		cache = apt.cache.Cache()

		for pkg in cache:
			if pkg.installed and pkg.candidate and pkg.installed != pkg.candidate:
				srcn = pkg.candidate.source_name
				if srcn in hit:
					continue

				hit[srcn] = 1

		ret = len(hit)

	except:
		ret = -1

	cache.close()
	print('packages=%d' % ret)

